### ISSUE TITLE
Feature: Show Time until next class is starting

### ISSUE THREAD

**Issue by patrickstecker** [patrickstecker/Vorlesungsplan#10]

**Comment by jstsddg** [comment]
Where should the time be shown?

Possible places:
- Inside the app on `MainActivity`
- Inside of a widget
- In a notification shortly before the class

**Comment by patrickstecker** [comment]
Trying to implement progress bar for every class displayed on the screen

**Comment by patrickstecker** [comment]
Implementing that the floating action button shows the Time until the next Class

**Comment by felixwortmann** [comment]
Is finished: closing this now
