### ISSUE TITLE
Enhancement: Change to-current-week icon

### ISSUE THREAD

**Issue by jstsddg** [patrickstecker/Vorlesungsplan#28]
Niclas noted that the to-current-week icon looks like a refresh icon.

**Comment by nclskfm** [comment]
https://material.io/resources/icons/?icon=home&style=round

https://material.io/resources/icons/?icon=restore&style=round

**Comment by jstsddg** [comment]
I think the home icon would be the best option.

**Comment by jstsddg** [comment]
Implemented in #31
