### ISSUE TITLE
Feature: Select other weeks

### ISSUE THREAD

**Issue by felixwortmann** [patrickstecker/Vorlesungsplan#6]
save week in [SharedPreferences](https://developer.android.com/training/data-storage/shared-preferences)

**Comment by patrickstecker** [comment]
A hard thing when providing the data from the website. We need to find out how the parameter date is calculated for that.

**Comment by jstsddg** [comment]
The `date` field in the URL is the unix timestamp in seconds, but the timezone is UTC+01:00.

Example:
- `1574636400` is `2019-11-24T23:00:00+00:00`
- `1574636400` is `2019-11-25T00:00:00+01:00`

But interestingly the timestamp is always floored to the nearest monday, thus `1574636399` is actually shown as `2019-11-18T00:00:00+01:00`.

**Comment by patrickstecker** [comment]
@MrKraboom How can we compute the timestamp then?

**Comment by jstsddg** [comment]
@patrickstecker
Java supports a system call to get the current unix timestamp in milliseconds, but as we need seconds we can easily convert them:
`date = System.currentTimeMillies() / 1000`

But as already mentioned this will show the old week even on Sunday, as the timestamp is always floored to the next monday, but we can just add one day to shift to the start of the week.
`date += 24*60*60`

**Comment by patrickstecker** [comment]
@MrKraboom Okay I will try that, thanks

Confusing is, that you can get to the same page by
https://vorlesungsplan.dhbw-mannheim.de/index.php?action=view&gid=3067001&uid=7431001&date=1574636399
and
https://vorlesungsplan.dhbw-mannheim.de/index.php?action=view&gid=3067001&uid=7431001&date=1574031600

**Comment by jstsddg** [comment]
- Timestamp `1574636399`
- UTC+00:00 `2019-11-24T22:59:59`
- UTC+01:00 `2019-11-24T23:59:59`
------------------------------------
- Timestamp `1574031600`
- UTC+00:00 `2019-11-17T23:00:00`
- UTC+01:00 `2019-11-18T00:00:00`
-------------------------------------
Yes, this behaviour is expected as the website will always **floor** to the nearest monday. The first timestamp is sunday (the 24th) at 23:59:59 (in UTC+01:00), thus the nearest monday is correctly identified as monday (the 18th) at 00:00:00 (in UTC+00:00), the second timestamp.

**Comment by patrickstecker** [comment]
@MrKraboom crazy shit, I am currently trying to find a method to get the current system time in seconds:D

**Comment by patrickstecker** [comment]
@MrKraboom Ehrenmann, its working:D

**Comment by jstsddg** [comment]
@patrickstecker
Nice, glad to help :D

**Comment by jstsddg** [comment]
@patrickstecker
I just noticed that we do not only need buttons to go forward and backward but also for returning to the current week.
Maybe you have already added this.

**Comment by patrickstecker** [comment]
You can now change the week
