### ISSUE TITLE
Feature: Use ical instead to get entries

### ISSUE THREAD

**Issue by felixwortmann** [patrickstecker/Vorlesungsplan#7]
Parse with [this](https://github.com/ical4j/ical4j)

https://vorlesungsplan.dhbw-mannheim.de/ical.php

**Comment by jstsddg** [comment]
I am not sure whether or not this really a better solution as the ical is not as rich as the website.

For example see [KW47 of TINF18AI2](https://vorlesungsplan.dhbw-mannheim.de/index.php?action=view&gid=3067001&uid=7431001&date=1574636399), day: friday.
The website contains additional information which the ical does not provide.
`Klausuraufsicht Herr [...]`

**Comment by patrickstecker** [comment]
@MrKraboom This is a good argument, the thing is that you can't identify the information clearly and 100% correctly, because the tags, in which the information is written, are sometimes changing. Are you sure, that the ical is not providing the information too? Couldn't it be that the Calendar is just not displaying the additional information?

**Comment by jstsddg** [comment]
@patrickstecker Yes, I checked the iCal file manually. The information I mentioned before are missing in the iCal (I searched the file with Ctrl+F and quickly looked by hand). Maybe we could use the iCal as base information and augment it with the website?

**Comment by patrickstecker** [comment]
@MrKraboom I think if we use both it is double work... I would suggest then to overwork gathering information from the website so that this is working well.

**Comment by jstsddg** [comment]
@patrickstecker Good point. Are you going to have a look at it? Then I might have a look at porting the application to rxKotlin.

**Comment by jstsddg** [comment]
I think we scrapped this idear, so we can close this issue?

**Comment by jstsddg** [comment]
As already discussed, we only use the website as the ical is missing some information (describtions).
