### ISSUE TITLE
Maintenance: Fastlane Release automation

### ISSUE THREAD

**Issue by felixwortmann** [patrickstecker/Vorlesungsplan#8]
Automate the release process using fastlane

https://docs.fastlane.tools/getting-started/android/release-deployment/#building-your-app

https://flutter.dev/docs/deployment/cd

https://developer.android.com/studio/publish/app-signing#sign-apk

**Comment by jstsddg** [comment]
We could use the git-flow workflow to simplify different releases. [Tutorial](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow)

ToDo:
- Invoke `git flow init`
- All fully implemented and merged feature branches should be removed from origin. See [git-flow cheatsheet](https://danielkummer.github.io/git-flow-cheatsheet/#features).

**Comment by felixwortmann** [comment]
Finished fastlane implementation

**Comment by jstsddg** [comment]
Maybe use GitHub actions? There is a possibility to save encrypted secrets

https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets
