### ISSUE TITLE
Feature: Countdown View

### ISSUE THREAD

**Issue by jstsddg** [patrickstecker/Vorlesungsplan#9]
Create a fullscreen view which shows a live countdown to the end of one `VorlesungsplanItem`.
Prefered time resolution: 10ms.

**Comment by felixwortmann** [comment]
[rxKotlin](https://github.com/ReactiveX/RxKotlin) would be useful for this

**Comment by jstsddg** [comment]
Suggestion: Move the complete project to a reactive design pattern (with rxKotlin) before adding the countdown view?

**Comment by jstsddg** [comment]
See #41

**Comment by jstsddg** [comment]
Implemented in #41
